name: PR test
on: 
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "event Pull request head: ${{github.event.pull_request.head}}"
          echo "event Pull request merge SHA: ${{github.event.pull_request.merge_commit_sha}}"
          echo "event ref: ${{github.event.ref}}"
          echo "github ref: ${{github.ref}}"
          echo "github.head ref: ${{github.head_ref}}"
          echo "github event name: ${{github.event_name}}"
          echo "github repository: ${{github.repository}}"
          echo "github repository owner: ${{github.repository_owner}}"