name: permissions yo
on: workflow_dispatch
permissions:
  pull-requests: read

jobs:
  first_job:
    env:
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    runs-on: ubuntu-latest
    name: dis first job yo first job
    steps:
      - name: first_step
        uses: actions/checkout@main
      - name: read some prs
        run: gh pr list
