name: matrix_workflow
on: 
  workflow_dispatch

jobs:
  escape_the_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        a: [1,2,3]
        b: ['a', 'b', 'c']
    steps:
      - name: first step yo
        run: |
          echo "a: ${{matrix.a}}, b: ${{matrix.b}}"