name: callr resuable workflwo
on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs: 
      response: ${{steps.first-step.outputs.response}}
    steps:
      - uses: ahmed33033/ts_action_test@main
        id: first-step
        with:
          prompt: 'was good famm'
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "::notice::output -- ${{needs.job1.outputs.response}}"